-- Certificates + public verification (blueprint §2 module 13, §7; spec §2.11, §2.12)
--
-- Certificate PDFs are generated by the template designer later; a certificate
-- can be issued now with a serial + verification code, and the public verify
-- endpoint returns only a minimal JSON status (never the PDF).

-- Minimal template row so certificates.template_id resolves; the visual editor
-- (react-konva) and layout JSON land with the template-designer module.
create table public.certificate_templates (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  name text not null,
  certificate_type text not null default 'course_completion'
    check (certificate_type in
      ('course_completion','hours_completion','skill_mastery','mock_exam_pass','enrollment_confirmation')),
  status template_status not null default 'draft',
  layout jsonb not null default '{}'::jsonb,
  layout_version int not null default 1,
  background_storage_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.certificate_templates (tenant_id, certificate_type);

create table public.certificates (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete restrict,
  template_id uuid references public.certificate_templates(id),
  learner_id uuid not null references public.learners(id),
  certificate_type text not null,
  verification_code text not null unique,     -- short, URL-safe (base32)
  serial_number text not null,                -- tenant-readable serial
  status certificate_status not null default 'active',
  issued_on date not null default current_date,
  valid_until date,
  storage_path text,                          -- generated PDF (later)
  enrollment_id uuid references public.enrollments(id),
  mock_exam_attempt_id uuid,
  issued_by uuid references public.users(id),
  revoked_at timestamptz,
  revoked_by uuid references public.users(id),
  revoked_reason text,
  supersedes_id uuid references public.certificates(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index on public.certificates (tenant_id, learner_id);
create index on public.certificates (tenant_id, status);

create trigger set_updated_at before update on public.certificate_templates
  for each row execute function public.tg_set_updated_at();
create trigger set_updated_at before update on public.certificates
  for each row execute function public.tg_set_updated_at();

-- ---------------------------------------------------------------------------
-- Public verification lookup (spec §2.12): SECURITY DEFINER so the anon role can
-- call it without any table read grant. Returns only a minimal status payload —
-- never the PDF, phone, or full name. Normalizes the code (strip dashes/case).
-- ---------------------------------------------------------------------------
create or replace function public.verify_certificate(p_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_norm text := upper(regexp_replace(coalesce(p_code, ''), '[^a-zA-Z0-9]', '', 'g'));
  c record;
begin
  select cert.status, cert.certificate_type, cert.issued_on, cert.valid_until,
         left(l.full_name, 1) as holder_initial, cert.learner_id, t.name as school_name
    into c
  from public.certificates cert
  join public.learners l on l.id = cert.learner_id
  join public.tenants t on t.id = cert.tenant_id
  where cert.verification_code = v_norm;

  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;

  return jsonb_build_object(
    'status', case
      when c.status = 'revoked' then 'revoked'
      when c.valid_until is not null and c.valid_until < current_date then 'expired'
      else 'valid'
    end,
    'certificate_type', c.certificate_type,
    'holder_initial', c.holder_initial,
    'issued_on', c.issued_on,
    'school_name', c.school_name
  );
end;
$$;
grant execute on function public.verify_certificate(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.certificate_templates enable row level security;
create policy "cert_templates_member_read" on public.certificate_templates
  for select to authenticated using (tenant_id = public.get_tenant_id_from_jwt());
create policy "cert_templates_admin_write" on public.certificate_templates
  for all to authenticated
  using (
    tenant_id = public.get_tenant_id_from_jwt()
    and public.get_role_from_jwt() = 'school_admin'
  )
  with check (
    tenant_id = public.get_tenant_id_from_jwt()
    and public.get_role_from_jwt() = 'school_admin'
    and public.tenant_is_writable()
  );
create policy "cert_templates_super_admin" on public.certificate_templates
  for all to authenticated
  using (public.is_super_admin_from_jwt()) with check (public.is_super_admin_from_jwt());

alter table public.certificates enable row level security;
-- Learner sees their own certificates.
create policy "certificates_self_read" on public.certificates
  for select to authenticated
  using (
    tenant_id = public.get_tenant_id_from_jwt()
    and learner_id = public.current_learner_id()
  );
create policy "certificates_staff_read" on public.certificates
  for select to authenticated
  using (tenant_id = public.get_tenant_id_from_jwt() and public.is_tenant_staff());
-- Issue/revoke happen via Edge Functions; super_admin bypass for platform ops.
create policy "certificates_super_admin" on public.certificates
  for all to authenticated
  using (public.is_super_admin_from_jwt()) with check (public.is_super_admin_from_jwt());

create trigger audit after insert or update or delete on public.certificates
  for each row execute function public.audit_row();
